###
### Display
###
# Verbose program output
verbose = false

# Show progress
progress = false


###
### Runtime
###
# Number of threads to utilize.
# Defaults to number of cores available to the system if omitted.
#threads = 2

# Maximum number of allowed redirects
max_redirects = 10

# Concurrency
max_concurrency = 1


###
### Requests
###
# User agent to send with each request
user_agent = "curl/7.71.1"

# Website timeout from connect to response finished
timeout = 20

# Comma-separated list of accepted status codes for valid links.
# Omit to accept all response types.
#accept = "text/html"

# Proceed for server connections considered insecure (invalid TLS)
insecure = false

# Only test links with the given scheme (e.g. https)
# Omit to check links with any scheme
#scheme = "https"

# Request method
method = "get"

# Custom request headers
headers = []


###
### Exclusions
###
# Exclude URLs from checking (supports regex)
exclude = [
  "myapi.com",
  "mydao.com",
  "staging.api3.eth.link",
  "infura.io",
  "api.coingecko.com/api/v3",
  "127.0.0.1",
  "coingecko.com/en/api/documentation",
  "contact@api3.org",
  "localhost:5000",
  "git@github.com",
  "your.heartbeat.service.io",
  "gateway.url",
  "eth-rinkeby.gateway.pokt.network",
  "execute-api.us-east-1.amazonaws.com",
  "github.com/.*.git",
  "api3.eth.link",
  "config@1.0.0",
  "config@0.3",
  "config@0.4",
  "config@0.5",
  "OIS@0.3",
  "ois@1.0",
  ".*/NOT-A-REAL-FILE.html",
  "@0.3",
  "@0.4",
  "@0.5",
  "etherscan.io",
  "goerli-faucet.mudit.blog"
]

# Exclude URLs contained in a file from checking
exclude_file = []

include = []

# Exclude all private IPs from checking
# Equivalent to setting `exclude_private`, `exclude_link_local`, and `exclude_loopback` to true
exclude_all_private = false

# Exclude private IP address ranges from checking
exclude_private = false

# Exclude link-local IP address range from checking
exclude_link_local = false

# Exclude loopback IP address range and localhost from checking
exclude_loopback = false

# Exclude all mail addresses from checking
exclude_mail = false
